### ISSUE TITLE
minio client not able to talk to secure minio server that uses self signed ssl certs

### ISSUE THREAD

**Issue by smothiki** [minio/mc#1220]
Started minio server with self signed certs 
```
minio --cert server.cert --key server.key  mode memory limit 512MB
Starting minio server on: https://127.0.0.1:9000
Starting minio server on: https://10.0.2.15:9000
Starting minio server on: https://172.17.8.100:9000
Starting minio server on: https://10.1.42.1:9000
2015/10/27 18:32:09 http: TLS handshake error from 172.17.8.100:40891: remote error: bad certificate
```
observed last message while tying to do ls on a bucket 
```
mc -C "/home/vagrant/.mc" --debug ls https://172.17.8.100:9000/pkg
mc: <ERROR> Unable to list target ‘https://172.17.8.100:9000/pkg’. x509: cannot validate certificate for 172.17.8.100 because it doesn't contain any IP SANs
 (4) .../home/minio/go/src/github.com/minio/mc/ls-main.go:116 main.mainList(..) Tags: [https://172.17.8.100:9000/pkg]
 (3) .../home/minio/go/src/github.com/minio/mc/ls-main.go:126 main.doListCmd(..) Tags: [https://172.17.8.100:9000/pkg]
 (2) .../home/minio/go/src/github.com/minio/mc/ls.go:129 main.doList(..)
 (1) .../home/minio/go/src/github.com/minio/mc/ls.go:123 main.doList(..)
 (0) .../home/minio/go/src/github.com/minio/mc/pkg/client/s3/s3.go:304 s3.(*s3Client).listInRoutine(..)
 Host:deis-01 | OS:linux | Arch:amd64 | Lang:go1.5 | Mem:3.6MB/7.4MB | Heap:3.6MB/5.0MB
vagrant@deis-01:~$ mc --debug ls https://172.17.8.100:9000/pkg
mc: <ERROR> Unable to list target ‘https://172.17.8.100:9000/pkg’. x509: cannot validate certificate for 172.17.8.100 because it doesn't contain any IP SANs
 (4) .../home/minio/go/src/github.com/minio/mc/ls-main.go:116 main.mainList(..) Tags: [https://172.17.8.100:9000/pkg]
 (3) .../home/minio/go/src/github.com/minio/mc/ls-main.go:126 main.doListCmd(..) Tags: [https://172.17.8.100:9000/pkg]
 (2) .../home/minio/go/src/github.com/minio/mc/ls.go:129 main.doList(..)
 (1) .../home/minio/go/src/github.com/minio/mc/ls.go:123 main.doList(..)
 (0) .../home/minio/go/src/github.com/minio/mc/pkg/client/s3/s3.go:304 s3.(*s3Client).listInRoutine(..)
 Host:deis-01 | OS:linux | Arch:amd64 | Lang:go1.5 | Mem:3.6MB/7.4MB | Heap:3.6MB/5.0MB
```
Tried with curl and working
```
curl --cert server.cert --key server.key --insecure  https://172.17.8.100:9000/pkg
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist.</Message><Resource>/pkg</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>vagrant
```
Let me know if I'm missing any thing. is there a way to configure mc to access certs

**Comment by harshavardhana** [comment]
> Let me know if I'm missing any thing. is there a way to configure mc to access certs

mc currently doesn't support self signed certificates, it used to support early in its days. But we removed it to keep things simpler. 

You can use 'mc' with standard SSL without using 'insecure' option for example - if you have a domain certificate signed by known SSL authorities. 

```
mc ls https://play.minio.io:9000
```

```
mc ls https://s3.amazonaws.com 
```

**Comment by smothiki** [comment]
Thanks. I'll try using a domain cert. Closing the issue.

**Comment by friday** [comment]
Lesson learned:

Minio client ("mc" and at least the node.js api) will not connect if your server is using self-signed certs, but in addition to this, the server won't serve via HTTP if the cert exists in ~/.minio/cert. So if you need to use self-signed certs, don't copy the cert and key into ~/.minio/cert. If you have, then remove them.

Instead, use a reverse proxy like Nginx or Caddy to handle the cert 

For Nginx: https://github.com/arschles/minio-howto/blob/master/setup-Nginx-proxy-with-Minio-Server.md
For Caddy, this Caddyfile should do it:

```
https://cdn.local.app {
  tls cdn.local.app.crt cdn.local.app.key
  proxy / localhost:9000 {
    transparent
  }
}
```

This way, you will be able to connect via the HTTP-address, but can serve content from the domain "cdn.local.app" via HTTPS

This is a shame. There are legit cases for self-signed certs, in particular as minio fits perfectly for local development when you want to host your own cloud storage, and real certs [is only possible for public hosts](https://www.digicert.com/internal-names.htm).

**Comment by vadmeste** [comment]
@friday mc and Minio server supports self-signed certificates, this is an old issue that was resolved long time ago.

By the way, you should put your self signed certificates under ~/.minio/certs (and not cert)

You can follow this https://docs.minio.io/docs/how-to-secure-access-to-minio-server-with-tls and get back to us here https://slack.minio.io for any difficulty.

**Comment by friday** [comment]
Thanks! "~/.minio/cert" was just a typo.

This is still happening to me:
```
Uncaught exception Error: self signed certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1104:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:638:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:468:38)
```

**Comment by vadmeste** [comment]
@friday self signed certificates are not really secure, that's why an error is thrown by default.

For mc, you can either pass --insecure flag, or you put your public certificate in ~/.mc/certs/CAs/

Can you open a separate issue for minio-js ? I believe that's also doable if you add some code.

Another solution is to configure your OS to trust your certificate.

**Comment by labnewbie** [comment]
When I run minio with certs I can't get the mc client to work.  The browser works via https on port 9000 but mc doesn't work even when I use the --insecure flag:

c:\minio>mc admin info myminio
mc: <ERROR> Cannot get service status. Failed to parse server response.
c:\minio>mc --insecure admin info myminio
mc: <ERROR> Cannot get service status. Failed to parse server response.

**Comment by vadmeste** [comment]
@labnewbie are you using recent Minio version ?
