### ISSUE TITLE
Show error during recursive cp data from s3

### ISSUE THREAD

**Issue by aisensiy** [minio/mc#2460]
The source s3 path has a structure like this:

```
.
├── 111.png
└── train
    └── test
        └── 111\\.png
```

The command is this:

```
$ mc cp -r s3/mybucket/data/ data/
```

## Expected behaviour

No Error at all, and all data downloaded into `data/` folder.

## Actual behaviour

```
mc: <ERROR> Failed to copy `xxxx/train/`. Object does not exist
mc: <ERROR> Failed to copy `xxxx/train/test/`. Object does not exist
```

## Steps to reproduce the behaviour

Create a s3 path look like below.

## mc version

2018-05-25T20:20:15Z

## System information

Docker, Mac OS 10.13.4

**Comment by harshavardhana** [comment]
Test with master branch 

```
$ aws s3 ls s3://aead/train/test/
2018-06-07 03:46:03         24 111\.png
2018-06-07 03:46:32         24 111\\.png


$ mc cp -r s3/aead/train/test/ /tmp/1/
...com/aead/train/test/111\\.png:  48 B / 48 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 58 B/s 0s

$ mc ls /tmp/1/
[2018-06-07 03:46:54 PDT]    24B 111\.png
[2018-06-07 03:46:54 PDT]    24B 111\\.png

```

Seems to be have been fixed

**Comment by aisensiy** [comment]
Are you sure this is done? I just tried `RELEASE.2018-06-09T02-18-09Z` it still failed.

```
mc: <ERROR> Failed to copy `https://s3.cn-north-1.amazonaws.com.cn/xxx/data/`. rename ./data/.part.minio ./data/: file exists
```

And in my example i have a directory another directory:

```
data directory:

├── 111.png
└── train
    └── test
        └── 111.png
```

**Comment by aisensiy** [comment]
@harshavardhana I verified this in master branch, got the same result

```
<ERROR> Failed to copy `https://s3.cn-north-1.amazonaws.com.cn/openbayes-datasets/aisensiy-273298efda6e1e6ef156ab1373dc6c001d6769aa/train/`. rename data/train/.part.minio data/train/: file exists
```

So it right now do not support --recursive copy even i give the flag `--recursive`.

**Comment by harshavardhana** [comment]
I am unable to reproduce this 

```
$ mc cp -r s3/aead/data/ /tmp/
.../aead/data/train/test/111.png:  48 B / 48 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 45 B/s 1s
```

```
mc ls -r s3/aead/data/
[2018-06-11 00:47:49 PDT]    24B 111.png
[2018-06-11 00:48:05 PDT]    24B train/test/111.png
```

Can you provide the output of the directory structure as `mc ls -r` output?

**Comment by aisensiy** [comment]
I can not reproduce this after I recreate the directory structure... I will close this one now.

**Comment by aisensiy** [comment]
I can reproduce the problem now. It fails when empty directory exists in s3. 

I know there is no real directory in s3, but I can make a fake one with 0 content and metadata. When mc get an empty directory it shows an error. I record my command line to demo the problem [https://asciinema.org/a/187049](https://asciinema.org/a/187049). The `/234` is a empty directory created in aws s3 page.

**Comment by aisensiy** [comment]
I just find another issues about this...

[https://asciinema.org/a/187053](https://asciinema.org/a/187053)

I go code by `go get -u github.com/minio/mc`

**Comment by aisensiy** [comment]
This is great. I appreciate this soooo much. 💯
