### ISSUE TITLE
mc cp -a not working on macos

### ISSUE THREAD

**Issue by william-plano-oxb** [minio/mc#2980]
## Expected behavior
if I call `mc cp -r -a foo local` then `mc cp -r -a local/foo foo_2` I should get a copy of the files in foo with their timestamps preserved.

## Actual behavior

I can call `mc cp -r -a foo local` successfully, but subsequently calling `mc cp -r -a local/foo foo_2` fails with errors "mc: <ERROR> Failed to copy 'blah'. Error in parsing file system attribute"

When I stat the file with `mc cp -r -a local/foo/blah` I see that the metadata is stored as:

```
  X-Amz-Meta-Mc-Attrs: atime:2019-12-04 11:07:31.90513642 +0000 GMT/ctime:2019-12-04 10:52:58.282475048 +0000 GMT/gid:20/gname:staff/mode:33252/mtime:2019-12-04 10:52:58.282475048 +0000 GMT/uid:501/uname:william.plano
```

## Steps to reproduce the behavior

```
mc cp -r -a foo local
mc cp -r -a local/foo foo_2
```

## mc version
built from source at 3f426ff7e064f41fe0daed03482bc55e3c6a4ccb

## System information
mac osx mojave 10.14.6 (18G1012)

**Comment by nitisht** [comment]
Thanks for reporting @william-plano-oxb we'll take a look

**Comment by harshavardhana** [comment]
Looks like the xattrs are not directly supported yet on macOS

**Comment by harshavardhana** [comment]
can you test this with latest release @william-plano-oxb ?

**Comment by harshavardhana** [comment]
Closing this as fixed in latest release.

**Comment by william-plano-oxb** [comment]
Hi, so sorry, I missed the previous message, I have tested this with mc.RELEASE.2020-01-25T03-02-19Z and the problem remains the same.

**Comment by harshavardhana** [comment]
Closing as duplicate of #3186
