### ISSUE TITLE
mc admin info TARGE, the result error

### ISSUE THREAD

**Issue by AkaiNoCat** [minio/mc#3284]
## Expected behavior
`mc admin info minio`
```bash
●  minio1:9000
   Uptime: 10 minutes
   Version: 2020-06-18T02:23:35Z
   Network: 4/4 OK
   Drives: 0/1 OK  # Expected behavior

●  minio3:9000
   Uptime: 10 minutes
   Version: 2020-06-18T02:23:35Z
   Network: 4/4 OK
   Drives: 1/1 OK

●  minio4:9000
   Uptime: 10 minutes
   Version: 2020-06-18T02:23:35Z
   Network: 4/4 OK
   Drives: 1/1 OK

●  minio2:9000
   Uptime: 10 minutes
   Version: 2020-06-18T02:23:35Z
   Network: 4/4 OK
   Drives: 0/1 OK # Expected behavior
```
## Actual behavior
`mc admin info minio`
```bash
●  minio1:9000
   Uptime: 10 minutes
   Version: 2020-06-18T02:23:35Z
   Network: 4/4 OK
   Drives: 1/1 OK   # Abnormal points

●  minio3:9000
   Uptime: 10 minutes
   Version: 2020-06-18T02:23:35Z
   Network: 4/4 OK
   Drives: 1/1 OK   

●  minio4:9000
   Uptime: 10 minutes
   Version: 2020-06-18T02:23:35Z
   Network: 4/4 OK
   Drives: 1/1 OK

●  minio2:9000
   Uptime: 10 minutes
   Version: 2020-06-18T02:23:35Z
   Network: 4/4 OK
   Drives: 1/1 OK  # Abnormal points
```
## Steps to reproduce the behavior
1. mc config host list
```
minio
  URL       : http://minio.example.com
  AccessKey : minio
  SecretKey : minio123
  API       : s3v4
  Lookup    : auto
```
2.docker-compose.yaml
```yaml
version: '2'
services:
  minio1:
    image: minio/minio:RELEASE.2020-06-18T02-23-35Z
    volumes:
    #  - /mnt1/minio1-1:/data1    # The key point
      - /mnt1/minio1-2:/cache1
    ports:
      - "9011:9000"
    cpuset: "1"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_CACHE: "on"
      MINIO_CACHE_AFTER: 1
      MINIO_CACHE_DRIVES: "/cache1"
      MINIO_CACHE_QUOTA: 80
      #MINIO_CACHE_EXCLUDE: "*.pdf,mybucket/*"
      MINIO_CACHE_WATERMARK_LOW: 70
      MINIO_CACHE_WATERMARK_HIGH: 90
    command: server http://minio{1...4}/data1

  minio2:
    image: minio/minio:RELEASE.2020-06-18T02-23-35Z
    volumes:
    #  - /mnt1/minio2-1:/data1   # The key point
      - /mnt1/minio2-2:/cache1
    ports:
      - "9012:9000"
    cpuset: "2"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_CACHE: "on"
      MINIO_CACHE_AFTER: 1
      MINIO_CACHE_DRIVES: "/cache1"
      MINIO_CACHE_QUOTA: 80
      #MINIO_CACHE_EXCLUDE: "*.pdf,mybucket/*"
      MINIO_CACHE_WATERMARK_LOW: 70
      MINIO_CACHE_WATERMARK_HIGH: 90
    command: server http://minio{1...4}/data1

  minio3:
    image: minio/minio:RELEASE.2020-06-18T02-23-35Z
    volumes:
      - /mnt1/minio3-1:/data1
      - /mnt1/minio3-2:/cache1
    ports:
      - "9013:9000"
    cpuset: "3"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_CACHE: "on"
      MINIO_CACHE_AFTER: 1
      MINIO_CACHE_DRIVES: "/cache1"
      MINIO_CACHE_QUOTA: 80
      #MINIO_CACHE_EXCLUDE: "*.pdf,mybucket/*"
      MINIO_CACHE_WATERMARK_LOW: 70
      MINIO_CACHE_WATERMARK_HIGH: 90
    command: server http://minio{1...4}/data1

  minio4:
    image: minio/minio:RELEASE.2020-06-18T02-23-35Z
    volumes:
      - /mnt1/minio4-1:/data1
      - /mnt1/minio4-2:/cache1
    ports:
      - "9014:9000"
    cpuset: "4"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_CACHE: "on"
      MINIO_CACHE_AFTER: 1
      MINIO_CACHE_DRIVES: "/cache1"
      MINIO_CACHE_QUOTA: 80
      #MINIO_CACHE_EXCLUDE: "*.pdf,mybucket/*"
      MINIO_CACHE_WATERMARK_LOW: 70
      MINIO_CACHE_WATERMARK_HIGH: 90
    command: server http://minio{1...4}/data1
```
3. nginx config
```
root@ip-172-30-1-169:~# cat /etc/nginx/conf.d/minio.conf
server {
 listen 80;
 server_name minio.example.com;

 # To allow special characters in headers
 ignore_invalid_headers off;
 # Allow any size file to be uploaded.
 # Set to a value such as 1000m; to restrict file size to a specific value
 client_max_body_size 0;
 # To disable buffering
 proxy_buffering off;

 location / {
   proxy_set_header X-Real-IP $remote_addr;
   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   proxy_set_header X-Forwarded-Proto $scheme;
   proxy_set_header Host $http_host;

   proxy_connect_timeout 300;
   # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
   proxy_http_version 1.1;
   proxy_set_header Connection "";
   chunked_transfer_encoding off;

   access_log /mnt/logs/minio/minio.access.log main;
   error_log /mnt/logs/minio/minio.error.log;

   proxy_pass http://minio; # If you are using docker-compose this would be the hostname i.e. minio
   # Health Check endpoint might go here. See https://www.nginx.com/resources/wiki/modules/healthcheck/
   # /minio/health/live;
 }
}
upstream minio {
  server 0.0.0.0:9011;
  server 0.0.0.0:9012;
  server 0.0.0.0:9013;
  server 0.0.0.0:9014;
}
```
## mc --version
- (paste output of `mc --version`)
mc version RELEASE.2020-06-20T00-18-43Z

**Comment by nitisht** [comment]
What is abnormal behaviour here @AkaiNoCat ?

**Comment by AkaiNoCat** [comment]
> What is abnormal behaviour here @AkaiNoCat ?

hi nitisht,  `mc admin info minio` should be displayed  2 drives online, 2 drives offline, when minio1,minio2  not volumes /data1
I executed it several times and found that the 'mc admin Info minio' result is not idempotent

**Comment by AkaiNoCat** [comment]
![image](https://user-images.githubusercontent.com/46026384/86472675-1dacb280-bd72-11ea-8b7d-8c8c53c6cde3.png)

**Comment by harshavardhana** [comment]
Please upgrade to latest MinIO we fixed issues in minio to ensure that offline disk is reported when a new drive is visible @AkaiNoCat

**Comment by AkaiNoCat** [comment]
> Please upgrade to latest MinIO we fixed issues in minio to ensure that offline disk is reported when a new drive is visible @AkaiNoCat

hi harshavardhana,thank u, I just updated the version, `image: minio/minio:RELEASE.2020-07-02T00-15-09Z`
the 'mc admin Info minio' result is idempotent,is good, but this `issue` still exists
when mino1,minio2 not mount volumes, mc get info is `Drivers 1/1 OK`,but prometheus/metrics show `minio_disks_total 0` 

![image](https://user-images.githubusercontent.com/46026384/86486123-13e47880-bd8d-11ea-9784-7e471762e27f.png)


Sorry, I didn't say what I was doing
I was simulating a situation where one or two disks were damaged, and the results were expected.
But we found that when minio1 and MiniO2 simulations were corrupted, "MC Admin Info minio" always showed 'Drivers 1/1 OK'

**Comment by harshavardhana** [comment]
> when mino1,minio2 not mount volumes, mc get info is `Drivers 1/1 OK`,but prometheus/metrics show `minio_disks_total 0`

this is because the drive exists but it is unformatted check `mc admin info --json` output

**Comment by AkaiNoCat** [comment]
> > when mino1,minio2 not mount volumes, mc get info is `Drivers 1/1 OK`,but prometheus/metrics show `minio_disks_total 0`
> 
> this is because the drive exists but it is unformatted check `mc admin info --json` output
Thank you, I see~

**Comment by kannappanr** [comment]
@AkaiNoCat Closing this issue as answered. Please feel free to reach out to us at https://slack.min.io for further questions.
