### ISSUE TITLE
Wrong healing status

### ISSUE THREAD

**Issue by AlexZIX** [minio/mc#3937]
Yesterday I've lost 2 of 12 drives in my distributed installation. I've replaced it and healing starts automatically. Today I want to review the healing status. I do it using mc:

root@minio-1:~# mc admin heal minio-cold
Objects Healed: 7,459/100,858 (7.3%), 49 GB/192 GB (25.3%)
Heal rate: 0 obj/s, 110 KiB/s
Estimated Completion: 2 weeks

It show me this output last 3 hours. At the same time I see that healing in progress because empty space on new drives getting smaller.

## Expected behavior
mc admin heal must show real healing statistics.

## Actual behavior
mc admin heal shows something.

## Steps to reproduce the behavior
Replace the drive with new one.

## mc --version
mc version RELEASE.2021-09-02T09-21-27Z

## System information
Linux minio-1 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by klauspost** [comment]
@AlexZIX Please upgrade to the latest minio version. We have made several adjustments to this since `2021-09-02`, likely it has been fixed.

If healing is progressing, I suggest to let it finish before upgrading. If you should encounter this issue again with the new version, feel free to open an issue.

**Comment by AlexZIX** [comment]
@klauspost Healing was finished few days ago and today I've updated my instance to the latest RELEASE.2022-02-18T01-50-10Z but still see this in heal command output:

root@minio-1:~# mc admin heal minio-cold
Objects Healed: 175,576/871,222 (20.1%%), 2.5 TB/12 TB (20.9%%)
Heal rate: 0 obj/s, 6.0 KiB/s
Estimated Completion: 2 months

**Comment by AlexZIX** [comment]
@harshavardhana this is output after 9 hours. Does that means that it's infinite process? What minio really tries to heal? I've replaced 4 of 12 disks, after 2 weeks all disks becomes filled with 1.1 TB of data and I thought that it's means that all disks was healed and my minio now in stable state. May be I can't understand something about how the healing works?

root@minio-1:~# mc admin heal minio-cold
Objects Healed: 175,665/871,368 (20.1%%), 2.5 TB/12 TB (20.9%%)
Heal rate: 0 obj/s, 6.5 KiB/s
Estimated Completion: 2 months
